### ISSUE TITLE
Animations ?

### ISSUE THREAD

**Issue by gamedever1** [nlebedenco/TPCE#10]
Where can I get animations for this project?

**Comment by nlebedenco** [comment]
It's been a while now and I currently don't have the time to advance this project for the time being but the animations I used during development were a mix of ALS2-3 and Kubold's. You can have your own animations but it's never going to be plug-and-play because you got to be mindful of starting/stopping frames, foot placement etc and then you have to put together your custom anim graph of course with you own character actions ans such. All this is true for any UE4 proj, though.
